version: '3'

services:
  database:
    image: postgres
    ports:
      - '5432:5432'
    container_name: bookStore
    volumes:
      - postgres-disk:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bookStore

volumes:
  postgres-disk:
